# Generated by Django 4.0.5 on 2023-07-26 04:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vehiculo', '0004_alter_vehiculo_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='vehiculo',
            options={'permissions': [('visualizar_catalogo', 'Puede visualizar el catálogo de vehículos'), ('add_vehiculomodel', 'Puede agregar un vehículo')]},
        ),
    ]
